name: Trigger Web Repo Update

on:
  push:
    branches:
      - feat/workflow-trigger-auto-update-dep  # or your default branch

jobs:
  trigger-web:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Web Repo
        run: |
          curl -i -v -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/plexicus/blog/dispatches \
            -d '{"event_type":"ui-lib-updated"}'